"""
Django settings for exampleocr project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from django.conf import settings  # Importar configuración de Django
from django.conf.urls.static import static  # Importar para servir archivos estáticos
from pathlib import Path  # Para manejar rutas
import os  # Importar para operaciones de sistema

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # Definir el directorio base del proyecto

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zm$p!5dvj5_id^4ht#3m9u4s#qivpx_(=#b#j-i0n-f$u98o2q'  # Clave secreta del proyecto

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Modo de depuración

ALLOWED_HOSTS = []  # Lista de hosts permitidos

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',  # Aplicación de administración
    'django.contrib.auth',  # Aplicación de autenticación
    'django.contrib.contenttypes',  # Para gestionar tipos de contenido
    'django.contrib.sessions',  # Manejo de sesiones
    'django.contrib.messages',  # Mensajes de retroalimentación
    'django.contrib.staticfiles',  # Manejo de archivos estáticos
    'ocr',  # Aplicación OCR
    'ckeditor',
    'ckeditor_uploader',
    #'tailwindcss',
    'compressor',
    'widget_tweaks',
]

# Configuración de CKEditor
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'height': 500,
        'width': '100%',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike', 'RemoveFormat'],
            ['NumberedList', 'BulletedList'],
            ['Link', 'Unlink', 'Image'],
            ['Source'],
        ],
    },
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Middleware de seguridad
    'django.contrib.sessions.middleware.SessionMiddleware',  # Middleware de sesiones
    'django.middleware.common.CommonMiddleware',  # Middleware común
    'django.middleware.csrf.CsrfViewMiddleware',  # Middleware para proteger contra CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Middleware de autenticación
    'django.contrib.messages.middleware.MessageMiddleware',  # Middleware de mensajes
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Middleware para evitar clickjacking
]

ROOT_URLCONF = 'exampleocr.urls'  # Configuración de las URLs raíz

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Backend de plantillas
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Directorio de plantillas
        'APP_DIRS': True,  # Usar directorios de plantillas de aplicaciones
        'OPTIONS': {
            'context_processors': [  # Procesadores de contexto para las plantillas
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'exampleocr.wsgi.application'  # Aplicación WSGI para el despliegue

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Motor de base de datos
        'NAME': 'ocr',  # Nombre de la base de datos PostgreSQL
        'USER': 'postgres',  # Usuario de PostgreSQL
        'PASSWORD': 'postgres',  # Contraseña de tu usuario PostgreSQL
        'HOST': 'localhost',  # Host de la base de datos
        'PORT': '5432',  # Puerto de la base de datos
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGE_CODE = 'en-us'  # Código de idioma
TIME_ZONE = 'UTC'  # Zona horaria
USE_I18N = True  # Activar la internacionalización
USE_TZ = True  # Usar zona horaria

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = 'static/'  # URL para archivos estáticos

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Tipo de campo primario por defecto

# Configuración de archivos multimedia
CKEDITOR_UPLOAD_PATH = "uploads/"  # Ruta para subir archivos con CKEditor
MEDIA_URL = '/media/'  # URL para archivos multimedia
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Directorio para almacenar archivos multimedia

LOGIN_REDIRECT_URL = 'home'  # URL a redirigir después de iniciar sesión
LOGOUT_REDIRECT_URL = 'welcome'  # URL a redirigir después de cerrar sesión

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'  # o donde almacenes los archivos estáticos de la app

COMPRESS_ROOT = BASE_DIR / 'static'
COMPRESS_ENABLED = True
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

LOGIN_URL = '/ocr/login/'  # Asegúrate de que coincida con la ruta a tu vista de login

