# Generated by Django 5.1.1 on 2024-09-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadosOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('texto_extraido', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resultadosocr',
            },
        ),
        migrations.CreateModel(
            name='Paginas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='paginas/')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='ocr.resultadosocr')),
            ],
            options={
                'db_table': 'paginasocr',
            },
        ),
    ]
