# Generated by Django 5.1.1 on 2024-10-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_resultadosocr_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadosocr',
            old_name='fecha_salida',
            new_name='fecha',
        ),
    ]
